import os
from dotenv import load_dotenv

load_dotenv()

TONEANALYZER_API_KEY = os.getenv('TONEANALYZER_API_KEY')
TONEANALYZER_API_URL = os.getenv('TONEANALYZER_API_URL')
TONEANALYZER_API_VER = os.getenv('TONEANALYZER_API_VER')

SEMANTICS_API_KEY = os.getenv('SEMANTICS_API_KEY')
SEMANTICS_API_URL = os.getenv('SEMANTICS_API_URL')
SEMANTICS_API_VER = os.getenv('SEMANTICS_API_VER')

SUTIME_JARS = os.path.join(os.path.dirname(__file__), 'jars')


# Conversation model states
START_STATE = 0
GREETING_STATE = 1
FEEDFORWARD_STATE = 2
CONVERSATION_STATE = 3
CONVERSATION_EXCEPT_STATE = 4
CONVERSATION_ABOUTME_STATE = 5
CONVERSATION_MYACTIVITY_STATE = 6
CONVERSATION_GENERAL_STATE = 7
CONVERSATION_ABOUTHUMAN_STATE = 8
CONVERSATION_HUMANACTIVITY_STATE = 9
FEEDBACK_STATE = 10
CLOSING_STATE = 11
END_STATE = 12
